2024用にデザインを変更
hibiya-itchief/quaint-wa pull request #14
Opened 2023-12-22 14:10 UTC by aozoraUS

cssがそれぞれのvueファイルで定義されていると管理しにくいので~/assets/css/main.cssに基本的なものを全てまとめました。それに伴ってnuxt.config.tsでcssを読み込むように少し変更しました。vuetifyのcolorの設定をtheme_colorとして設定してsairaiになっている部分の全てをこれに置き換えました。一部2024用に表記を変更しました。

2023-12-23 05:42 UTC, hibiyahibiyahibiya requested changes
まじありがとう！！！！有能！！！！！！
起きたらReviewの通知が来ててめちゃうれしかった

main.css方式良いと思う！！あとは些細なところの修正だけだからよろしく！！！

2023-12-23 05:42 UTC, hibiyahibiyahibiya commented on assets/css/main.css
> +.info-title {
info-titleがpages/index.vue内のstyleにまだ残ってて重複してるのを消しといて！
info-subtitleとか、他のもいくつか重複してたから、vscodeで検索かけた方がいいかも

2023-12-23 05:42 UTC, hibiyahibiyahibiya commented on assets/css/main.css
> +.info-title {
あと、main.cssに移管するものとしないものの基準はどういうイメージで考えてる？

2023-12-23 05:42 UTC, hibiyahibiyahibiya commented on pages/help.vue
> +                  <v-icon large color="theme_color"
他のページもそうだけど、まだ祭徠色 #b49656 が残ってるところがあるから、
vscode内で検索かけて殲滅してもらいたい！

2023-12-23 09:48 UTC, aozoraUS commented
カラー変更しました

2023-12-23 11:37 UTC, hibiyahibiyahibiya requested changes
元画像
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/40398a1a-8646-43cf-b0c4-fedcf64c3b15)


新画像
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/f6f4758b-0ada-4d09-87fb-d7112d003fc6)
css効いてない……？

あと、titleとかpages-titleとか、class名の可読性がかなり低くなってるから、名前考えないとねー……

2023-12-23 13:17 UTC, aozoraUS commented
フォントが変わってないバグを直しました

2023-12-23 13:37 UTC, hibiyahibiyahibiya commented
何で治ったんだろう…？？
もしかしてVuetifyがtitleって名前のclassを使ってたりしてたのかなあ

class名の可読性は後でissueにする？それとも今解決しちゃう？

2023-12-24 06:32 UTC, aozoraUS commented
groupsのページをcomponent使ったものに置き換えました。cssのクラス名は今のところ問題ないと思うので、後々修正するでいいと思います。

2023-12-24 07:54 UTC, hibiyahibiyahibiya approved these changes
Approve

cssのクラス名については了解、近いうちに直そう

2023-12-24 11:16 UTC, aozoraUS commented
競合した部分を無視してマージしようとしたら弾かれたっぽいです

2023-12-24 11:40 UTC, hibiyahibiyahibiya commented
GroupCard.vue内、theme_colorに直しといてほしい
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/9da00aa9-a901-47ab-90a1-8ff74ea16aec)

あとlintエラー出てる

2023-12-24 14:09 UTC, aozoraUS commented
theme_colorの設定は直しました

2023-12-24 14:25 UTC, hibiyahibiyahibiya approved these changes
OKだと思う！！！とても感謝！！

2023-12-24 21:48 UTC, merged