団体の画像の縦横比
hibiya-itchief/quaint-wa pull request #20
Opened 2024-01-07 23:18 UTC by aozoraUS

団体の画像の縦横比を縦：横=4:3で設定しました。それに伴ってグループの表示する列の数を調整しました。

2024-01-08 02:03 UTC, hibiyahibiyahibiya requested changes

2024-01-08 02:03 UTC, hibiyahibiyahibiya commented on components/GroupCard.vue
> +            style="font-size: 18px"
このxsとそれ以外との分岐、文字の大きさpxの違いだけだから、なんかどうにかしてうまくまとめたいなー
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/314d7f2a-fe2d-4fa9-84bb-c6b7be08d774)
↑参考として、breakpointでclassを分岐するやり方

ただ、かえって可読性が下がりそうだったら考えなきゃね

2024-01-08 02:03 UTC, hibiyahibiyahibiya commented on pages/groups/index.vue
> +      }
ちなみに、いまGroupCard.vue内のstorage_bookmarkはファイル内で定義されたあとlocalstorageの内容が代入されてないからブックマーク機構は動作していない
と思ってるんだけど、実際そこんところどうなのかな

2024-01-08 04:50 UTC, aozoraUS commented
タイトルの部分を修正しました！フォントサイズの変更はとりあえずみやすくはできたと思います。localstorageの部分はぱっと見でおかしいと思った部分を直しただけなので実はあまりよくわかってないです

2024-01-08 06:07 UTC, hibiyahibiyahibiya commented on components/GroupCard.vue
>            {{ group.description }}
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/5c6f45c3-0800-442f-80e1-66ff7e6fed03)
これPC表示なんだけど、タグ(2年生)の下に空白ができちゃってるから、できたらその分descriptionを何行か表示できたら……って思っちゃうな
ただちょっと大変そうではある

2024-01-08 06:07 UTC, hibiyahibiyahibiya commented on components/GroupCard.vue
> +            $vuetify.breakpoint.xs ? 'font-size: 14px' : 'font-size: 18px'
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/baaf6c5d-5d05-41cc-8db3-67d8a5254bf4)
これPC表示なんだけど、titleとgroupnameの大きさが近くて見づらい……？
でもこれは感性によると思う

2024-01-08 06:07 UTC, hibiyahibiyahibiya commented on pages/groups/_groupId/edit/index.vue
> +                  画像は縦横比が縦:横=4:3のもの（なるべくそれに近しいもの）を設定してください。サイズが合わず小さく表示されてしまう場合があります。
記憶力いい

2024-01-08 10:03 UTC, aozoraUS commented
ブックマークは動くようにしました。
複数行表示するやつを、多くタグがついたときも高さが均等になるように無理やり実装しましたが、これはどうなのでしょうか？( ；∀；)

2024-01-08 11:37 UTC, hibiyahibiyahibiya requested changes
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/090e58d1-5965-4b6c-ab18-7c764d2c6a1e)
PC表示が２列(正しくは３列)になっちゃってるのと、下空間あるのに１行のままだね(サマーウォーズ)

でも正直、タグについてはまだ扱いが決まってないからタグ１個だけを想定した表示でもいいかって思ってきちゃった
ただサイズ的にPC表示だとdescriptionは２行にしてほしいけどね

ブックマークはうまく機能してる！ないす

2024-01-08 13:05 UTC, aozoraUS commented
修正しました

2024-01-08 13:20 UTC, hibiyahibiyahibiya commented
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/d7a39113-ac93-4e6f-b351-0d476539947f)
２列なのは意図した仕様？

あと、些細なんだけど、GroupCard内、storage_bookmarks→storageBookmarks、とlowerCamelCaseにしてくれないかな

2024-01-08 14:50 UTC, aozoraUS commented
2列か３列かは意図したように変更できます。また後日試してみますが多分cols=6とすると表示がバグると思います。変数名も変更しておきます・ω・

2024-01-09 11:46 UTC, aozoraUS commented
変数名を変更しました。
cols="6" xs="12"試してみたらこうなりました
<img width="413" alt="スクリーンショット 2024-01-09 20 42 36" src="https://github.com/hibiya-itchief/quaint-wa/assets/74809407/199abc03-7410-42a1-9a8b-3ce30a893da7">
<img width="857" alt="スクリーンショット 2024-01-09 20 42 27" src="https://github.com/hibiya-itchief/quaint-wa/assets/74809407/facc47b4-1fbd-4eb0-9459-6d5fb3622f7b">
スマホ表示の時にカードが一行に２列表示されてしまう感じでした

2024-01-09 12:39 UTC, hibiyahibiyahibiya commented
なんか今度はgroups/index.vueの方で出てるｗｗ
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/9cd0de45-feda-4dae-9f4f-2c07059c4b3c)
諦めるか、それか別の一単語の名前の変数にしてもらうしかなさそうｗｗｗ

それと、スマホ以外の表示、２列にする？おれ的には３列の方が好みではあるんだけど(もともと４列だったし)

2024-01-09 13:41 UTC, aozoraUS commented
変数名の単語の切れ目をハイフンで繋げと言われているようですが、typescript内で変数名をハイフンで区切るとバグになるようなので、もうこのままstorageBookmarksで押し通すでいい気がします、、、、。

2024-01-09 13:45 UTC, aozoraUS commented
lgサイズ未満だとあまりにも一つのカードが小さくなってしまうのでlgサイズから３列に変更しました
![Uploading スクリーンショット 2024-01-09 22.42.36.png…]()

2024-01-09 20:15 UTC, hibiyahibiyahibiya approved these changes
おっけーい！！ありがとう！！！

余談、Surfaceずっとmdだと思ってたんだけどぎりぎりlgみたい
![image](https://github.com/hibiya-itchief/quaint-wa/assets/128669695/300dce7a-e96c-4ee9-83eb-12419c7d80cb)

2024-01-09 22:22 UTC, merged